### ISSUE TITLE
USB information

### ISSUE THREAD

**Issue by DerFetzer** [s0len0id/smartpad-tester#1]
Dear @s0len0id,

I am currently working on reverse engineering the MIDIPLUS SmartPAD.
You can see the progress in my [repository](https://github.com/DerFetzer/open-smartpad).

Unfortunately I forgot to save information of the USB endpoints and so on of the original firmware.
Do you still own the SmartPAD? If so, yould you maybe upload this information to your respository?

I would be most interested in relevant output of the following command:
`lsusb -vvv` (Linux)
I don't know if there is as Windows command for this.

Thank you in advance!

Yours,
DerFetzer

**Comment by s0len0id** [comment]
Cool!
Yes, still got it, with the upgraded v15 firmware (selecting colors over midi works now). 
Will check tomorrow.

**Comment by DerFetzer** [comment]
Nice! Thank you very much!

**Comment by s0len0id** [comment]
See notes/smartpad-lsusbvvv-015.txt, is this what you need?

**Comment by DerFetzer** [comment]
Yes, exactly! Thank you very, very much!
